### ISSUE TITLE
Remote Test Does Not Start When PR Is Set to “Ready to Review”

### ISSUE THREAD

**Issue by rswrz** [cloudeteer/terraform-governance#56]
When a Pull Request is in “Draft” status, the remote test does not start as intended (implemented in #52). However, the remote test also fails to start when the PR is moved to “Ready to Review,” which is incorrect behavior.

**Comment by rswrz** [comment]
It is actually a module template issue. I will fix that in https://github.com/cloudeteer/terraform-module-template

**Comment by rswrz** [comment]
Done in module template, we also have to change implement this change in every existing module repository.

https://github.com/cloudeteer/terraform-module-template/pull/17/commits/eef1281041d79eb2e1d6ef996224a60f8f0ce1bf

**Comment by neonwhiskers** [comment]
wanted to solve this but @lixhunter  already did as it seems :)

**Comment by lixhunter** [comment]
> wanted to solve this but [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/4758198?s=64&amp;u=803bab090ece73f0336be22848dd610237f9d4da&amp;v=4">@lixhunter](https://github.com/lixhunter) already did as it seems :)
> 
> can you confirm?

Yes, @neonwhiskers. This is solved with:

- https://github.com/cloudeteer/terraform-governance/pull/52
- https://github.com/cloudeteer/terraform-module-template/pull/17
