### ISSUE TITLE
Improve CI workflow

### ISSUE THREAD

**Issue by rswrz** [cloudeteer/terraform-governance#58]
Currently, a reusable workflow executes all jobs multiple times during various events in the PR lifecycle:

- PR created: All sub-workflows are executed.
- PR label added: All sub-workflows are re-executed (including tests).
- Code changes pushed to the PR: All sub-workflows are executed again.
- PR merged: Before the release, all tests are executed again, followed by the release process. This also applies if changes are pushed directly to the main branch.

This behavior is highly inefficient and negatively impacts performance. We need a more optimized solution to reduce redundant workflow executions.

```[tasklist]
### Update Terraform module workflow usages and remove from project workflow
- [x] [terraform-azurerm-helloworld](https://github.com/cloudeteer/terraform-azurerm-helloworld)
- [x] [terraform-module-template](https://github.com/cloudeteer/terraform-module-template)
- [x] [terraform-azurerm-vm](https://github.com/cloudeteer/terraform-azurerm-vm)
- [x] [terraform-azurerm-applicationgateway](https://github.com/cloudeteer/terraform-azurerm-applicationgateway)
- [x] [terraform-azurerm-launchpad](https://github.com/cloudeteer/terraform-azurerm-launchpad)
- [x] [terraform-azurerm-mssql-vm](https://github.com/cloudeteer/terraform-azurerm-mssql-vm)
- [x] [terraform-azurerm-avd](https://github.com/cloudeteer/terraform-azurerm-avd)
```

**Comment by rswrz** [comment]
> [!IMPORTANT]
> The automatic plan on pull requests should be refactored. We need to implement a quality gate before a plan (and apply) is actually executed to ensure that only validated changes are run.

**Comment by lixhunter** [comment]
prepared the workflow in https://github.com/cloudeteer/terraform-governance/pull/53

When it is merged we can move pull request an github release related workflows from module-ci to module-github.
